services:
  code-switch:
    build:
      context: .
      args:
        INSTALL_GPU: "${INSTALL_GPU:-false}"
    image: bilingual-code-switch-${TARGET:-cpu}
    command: jupyter lab --ip='*' --NotebookApp.token='' --NotebookApp.password='' --no-browser
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
    - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-}
    runtime: ${RUNTIME:-}
