services:
  code-switch:
    build:
      context: .
      args:
        INSTALL_GPU: "${INSTALL_GPU:-false}"
    image: bilingual-code-switch-${TARGET:-cpu}
    command: >
      sh -c "jupyter lab --ip='*' --NotebookApp.token='' --NotebookApp.password='' --no-browser &
             tensorboard --logdir /app/notebooks --host 0.0.0.0 --port 6006"
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - .:/app
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-}
    runtime: ${RUNTIME:-}
